[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DecisionTree = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
MLJModels = "d491faf4-2d78-11e9-2867-c94bc002c0b7"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
PrettyPrinting = "54e16d92-306c-5ea0-a30b-337be88ac337"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
ScientificTypes = "321657f4-b219-11e9-178b-2701a2544e81"
ScikitLearn = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
DecisionTree = "^0.8"
GLM = "^1.3"
MultivariateStats = "^0.7"
NearestNeighbors = "^0.4"
PrettyPrinting = "^0.1"
PyPlot = "^2.8"
RDatasets = "^0.6"
ScientificTypes = "^0.2"
ScikitLearn = "^0.5"
StatsBase = "^0.32"
