[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LightGBM = "7acf609c-83a4-11e9-1ffb-b912bcd3b04a"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
PrettyPrinting = "54e16d92-306c-5ea0-a30b-337be88ac337"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
